name: pyamrfinder
version: 'latest'
version-script: git describe --abbrev=1 --tags
summary: amr gene finder
description: |
  pyamrfinder is an open source desktop application

base: core18
grade: stable
confinement: strict
icon: gui/icon.png

apps:
  pyamrfinder:
    command: desktop-launch $SNAP/bin/pyamrfinder
    plugs: [desktop,desktop-legacy,unity7,home]
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/ncbi-blast+  
parts:
  pyamrfinder:
    plugin: python
    python-version: python3
    source: ../
    stage-packages:
      [python3-tk,xsel,ncbi-blast+,clustal,
      fontconfig-config,fonts-freefont-ttf,ttf-ubuntu-font-family,
      fonts-liberation]
    after: [desktop-glib-only]

  files: #to deal with problem finding init.tcl
    plugin: dump
    source: /usr/share/tcltk/
    organize:
         '*': ./usr/lib/
